projectType: extension
mavenAdditionalArgs: -pl mule-http-connector
mavenTool: 3.9.2
additionalTestConfigs:
  functionalJava17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -pl functional-tests/cors,functional-tests/http -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE
  munitJava17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -pl mule-http-connector -DruntimeProduct=MULE_EE -DruntimeVersion=4.6.0-SNAPSHOT -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE
