projectType: extension
mavenTool: "3.9.5"
devBranchesRegex: "1.10.0-TEST-DEPS-IN-PUBLIC-REPOS"
additionalTestConfigs:
  testsJava17:
    testJdkTool: OPEN-JDK17
    # TODO W-16243181 - set `munitMinMuleVersion` to 4.6.0
    mavenAdditionalArgs: -DskipMunitTests -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
