projectType: extension
mavenTool: "3.9.5"
additionalTestConfigs:
  testsJava17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeProduct=MULE_EE -DruntimeVersion=4.7.0-SNAPSHOT -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
