projectType: extension
mavenTool: "3.9.5"
additionalTestConfigs:
  testsJava17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DskipMunitTests -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
  testNetty:
    mavenAdditionalArgs: -DruntimeVersion=4.8.0-SNAPSHOT -DruntimeProduct=MULE_EE -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.http.service.implementation=NETTY
