projectType: extension
mavenTool: "3.9.9"

mavenAdditionalArgs: -pl mule-http-connector -DfailIfNoTests=false -Dmunit.test=listener/all-interfaces-test-case.xml

additionalTestConfigs:
  munitTests:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -pl mule-http-connector -DfailIfNoTests=false -Dmunit.test=listener/all-interfaces-test-case.xml -DmunitMinMuleVersion=4.6.0 -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
  functionalTests:
    jdkTool: OPEN-JDK17
    mavenAdditionalArgs: -pl functional-tests/http -DfailIfNoTests=false -Dtest=HttpStreamingTestCase -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
