projectType: extension
mavenTool: "3.9.9"

jdkTool: OPEN-JDK17
testJdkTool: OPEN-JDK17
mavenAdditionalArgs: -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true

additionalTestConfigs:
  mtf-jdk8:
    testJdkTool: OPEN-JDK8
    mavenAdditionalArgs: -pl mule-http-connector -DskipUnitTests=true
# TODO W-17496009
#  mtf-jdk11:
#    testJdkTool: OPEN-JDK11
#    mavenAdditionalArgs: -pl mule-http-connector -DskipUnitTests=true
  jdk21:
    testJdkTool: TEMURIN-JDK21
  netty-functionalTests:
    mavenAdditionalArgs: -pl functional-tests,functional-tests/http,functional-tests/cors -Dmule.http.service.implementation=NETTY -Drevapi.skip
  netty-munitTests:
    mavenAdditionalArgs: -pl mule-http-connector -Dmule.http.service.implementation=NETTY -DmunitMinMuleVersion=4.9.0 -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
