projectType: extension
mavenTool: "3.9.9"

mavenAdditionalArgs: -pl .,mule-http-connector

additionalTestConfigs:
  functionalTests:
    jdkTool: TEMURIN-JDK21
    mavenAdditionalArgs: -pl functional-tests,functional-tests/http,functional-tests/cors -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
  munitTests:
    testJdkTool: TEMURIN-JDK21
    mavenAdditionalArgs: -pl mule-http-connector -DmunitMinMuleVersion=4.6.0 -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
  netty-functionalTests:
    jdkTool: TEMURIN-JDK21
    mavenAdditionalArgs: -pl functional-tests,functional-tests/http,functional-tests/cors -Dmule.http.service.implementation=NETTY -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
  netty-munitTests:
    testJdkTool: TEMURIN-JDK21
    mavenAdditionalArgs: -pl mule-http-connector -Dmule.http.service.implementation=NETTY -DmunitMinMuleVersion=4.9.0 -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.jvm.version.extension.enforcement=LOOSE -Dmule.module.tweaking.validation.skip=true
